### ISSUE TITLE
i am not sure i understand the usage of this?

### ISSUE THREAD

**Issue by shez1983** [maxalmonte14/magicproperties#2]
at the top it states:
'you call getters and setters implicitly in PHP. ' 

implicitly to me means i dont have to define a getter/setter for each property and it should work out of the box... but this package requires you to define them - so what is the point of this package?

**Comment by maxalmonte14** [comment]
Hi @shez1983 thanks for posting your question.

This package allows you calling getters/setters implicitly but is necessary declare it before.

For example, when you create a new object (in any OO language) the constructor is called implicitly, you don't need to do 

```php
$myObject->__construct();
```

This is totally wrong, the constructor is called automatically when you create an object instance, the way that magic properties works is similar. Imagine the next example:

```php
class User
{
    private $name;

    public function setName($newName)
    {
        if (!is_str($newName)) {
            throw new InvalidArgumentException('The name property must be a string');
        }
        $this->name = $newName;
    }
}
```

Without magic properties you have to access to your setter method **explicitly**, that is:

```php 
$user->setName('Peter');
```

With magic properties the only thing you need to do is call your property in your instance object, if it is present in the *settable* array then your setter is called automatically:

```php
/**
* This call your setter method
*/
$user->name = 'Peter';

/** 
* If you try to do the following
* an InvalidArgumentException is
* thrown because is the way you
* defined it in your setter
*/
$user->name = 5;
```

What is the point of using magic properties? Maybe you think using magic properties doesn't make sense, that define as public your properties is enough, but if you simply declare your properties as public, you can't manipulate the data before getting or setting.

Maybe you feel comfortable defining and calling your getters/setters over and over again, but with magic properties you can do exactly that in a more short and readable way.

**Comment by shez1983** [comment]
thanks for the kind explanation :)
